name: teste-itau

services:

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: always
    ports:
      - "8080:8080"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - prometheus-data:/prometheus:rw
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./docker/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana:rw
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/:ro
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  grafana-data: {}
  prometheus-data: {}
